# password generator with regex 
# PASSWORD SHOULD BE MINIMUM OF 6 CHARACTERS LONG 
# PASSWORD SHOULD HAS MINIMUM 2 LETTERS 
# PASSWORD SHOULD HAS MINIMUM 2 NUMBERS 
# PASSWORD SHOULD HAS MINIMUM 2 CHARACTERS EXCEPT SPACE 
# ASK HOW MANY LETTERS USER WANT TO 
# ASK HOW MANY NUMBERS USER WANT TO

# MAIN PROGRAM
# 1. PASSWORD GENERATOR
# 2. PASSWORD CHECKER
# 3. EXIT

# PASSWORD GENERATOR
# 1. GET HOW MANY LETTERS USER WANT TO ---> MIN=2, IF LESS TRY AGAIN
# 2. GET HOW MANY NUMBERS USER WANT TO ---> MIN=2, IF LESS TRY AGAIN
# 3. GET HOW MANY CHARACTERS USER WANT TO --> MIN=2, IF LESS TRY AGAIN
# 4. FUNCTION GENERATEPASSWORD() WILL GENERATE PASSWORD
# 5. COPY PASSWORD TO THE CLIPBOARD AND PRINT INFORMATION

# PASSWORD CHECKER
# 1. GET THE PASSWORD FROM THE USER
# 2. CHECK IF IT IS STRONG
# 3. PRINT RESULT

# MAIN PROGRAM
# IMPORTING MODULES
import re
import random
import pyinputplus as pyip

inputMenu = pyip.inputChoice(['1', '2', '3', 'PASSWORD GENERATOR', 'PASSWORD CHECKER', 'EXIT'], '1. PASSWORD GENERATOR\n2. PASSWORD CHECKER\n3. EXIT\n')

while inputMenu != 'EXIT' or inputMenu != '3':
    if inputMenu == 'PASSWORD GENERATOR' or inputMenu == '1':
        # PASSWORD GENERATOR
    elif inputMenu == 'PASSWORD CHECKER' or inputMenu == '2':
        # PASSWORD CHECKER
